version: 18
jobs:
- name: Build
  jobExecutor: system76
  steps:
  - !CommandStep
    name: manual checkout
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - git clone --recurse-submodules ssh://onedev/bloggit .
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: make
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - if [ -f "/etc/bash.bashrc" ]; then source "/etc/bash.bashrc"; fi # load nix env vars if available
      - if [ -f "/etc/bash.bashrc" ]; then source "/etc/bash.bashrc"; fi # load nix env vars if available
      - if ! which nix-build; then echo "nix is required but not installed" && env && echo "$PATH" && exit 1; fi
      - echo $PATH
      - which nix-build
      - make urbit
      - make all
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: -prod
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: Deploy
  jobExecutor: system76
  steps:
  - !CommandStep
    name: manual checkout
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - git clone --recurse-submodules ssh://onedev/bloggit .
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: deploy
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - make all
      - make deploy
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: prod
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
