version: 18
jobs:
- name: Build
  jobExecutor: system76
  steps:
  - !CommandStep
    name: manual checkout
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - echo "ls -al $(pwd):"
      - ls -al
      - git init
      - git remote add origin ssh://onedev/bloggit
      - git pull origin main
      - git submodule update --init --recursive modules/urbit
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: make
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - make all
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: -prod
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  caches:
  - key: npm
    path: .npm/_cacache
  - key: node_modules
    path: node_modules
  - key: cache
    path: .cache
  timeout: 3600
- name: Deploy
  jobExecutor: system76
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !SshCredential
      keySecret: oneagent-key
    withLfs: false
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: deploy
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - make all
      - make deploy
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: prod
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  caches:
  - key: npm
    path: .npm/_cacache
  - key: node_modules
    path: node_modules
  - key: cache
    path: .cache
  timeout: 3600
