#!/bin/bash

root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
project="$(jq .name "$root/package.json" | tr -d '"')"

cmd="$1"
shift;

# make sure the builder is built
docker build --file ops/builder/Dockerfile --tag "${project}_builder" ops/builder

# TODO: building docker images needs to happen on the host machine, not in the builder
if [[ "$cmd" == "build" ]]
then bash ops/maketh.sh "$@"

elif [[ "$cmd" == "push" ]]
then echo "$cmd not implemented yet"

elif [[ "$cmd" == "pull" ]]
then echo "$cmd not implemented yet"

else echo "$cmd not implemented yet"

fi
